//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Addendas
    {
        public System.Guid IdAddenda { get; set; }
        public string NombreAddenda { get; set; }
        public string XML { get; set; }
        [DataType(DataType.Date)]
       // [Display(Name = "Fecha de Registro")]
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Estado { get; set; }
    }

    public class pdf
    {
        public string cfdi64 { get; set; }

        public string cfdiState { get; set; }
        public string isFree { get; set; }
        public string logo64 { get; set; }
        public string informacionAdicional { get; set; }
        public string infoNofiscal { get; set; }
    }
}
